### ISSUE TITLE
Release Checklist for `v4`

### ISSUE THREAD

**Issue by avik-pal** [SciML/NonlinearSolve.jl#481]
## Pre-Release Checklist

 - [x] Package Registrations
   - [x] NonlinearSolveBase https://github.com/JuliaRegistries/General/pull/117897
   - [x] BracketingNonlinearSolve https://github.com/JuliaRegistries/General/pull/118130
   - [x] SimpleNonlinearSolve v2
   - [x] NonlinearSolveFirstOrder
   - [x] NonlinearSolveSpectralMethods
   - [x] NonlinearSolveQuasiNewton
 - [x] NonlinearSolve uses all of the above packages
 - [x] Deprecate unicode APIs
 - [x] Pre-Conditioners: https://github.com/SciML/NonlinearSolve.jl/pull/462

## Post-Release Checklist

 - [ ] Downstream Compat Updates
 - [ ] Re-enable MTK docs

**Comment by ChrisRackauckas** [comment]
Downstream compats:

- [ ] https://github.com/SciML/SciMLBenchmarks.jl/pull/1114
- [ ] https://github.com/SciML/SciMLBenchmarks.jl/pull/1113
- [ ] https://github.com/SciML/SciMLBenchmarks.jl/pull/1112
- [ ] https://github.com/SciML/SciMLBenchmarks.jl/pull/1111
- [ ] https://github.com/SciML/ModelingToolkit.jl/pull/3178
- [ ] https://github.com/SciML/ModelingToolkit.jl/pull/3177
- [ ] https://github.com/SciML/ModelingToolkit.jl/pull/3176
- [ ] https://github.com/SciML/Catalyst.jl/pull/1109
- [ ] https://github.com/SciML/SciMLBase.jl/pull/843
- [ ] https://github.com/SciML/SciMLDocs/pull/254
- [ ] https://github.com/SciML/DelayDiffEq.jl/pull/296
- [ ] https://github.com/SciML/DeepEquilibriumNetworks.jl/pull/169
- [ ] https://github.com/SciML/OrdinaryDiffEq.jl/pull/2510
- [ ] https://github.com/SciML/DiffEqDocs.jl/pull/766
- [ ] https://github.com/SciML/DifferentialEquations.jl/pull/1063
- [ ] https://github.com/SciML/OrdinaryDiffEq.jl/pull/2509

**Comment by avik-pal** [comment]
In most cases, packages shouldn't see a problem, the main change was termination conditions from DiffEqBase cannot be used

**Comment by Datseris** [comment]
Are there any breaking changes for front-end users downstream? Or can we just bump the compat to 4 without worry?

**Comment by avik-pal** [comment]
@Datseris if you were interacting with NonlinearSolve without changing the `termination_condition` kwarg, it should be safe to bump. https://docs.sciml.ai/NonlinearSolve/dev/release_notes/#Oct-'24 has more details
